### ISSUE TITLE
JSON attributes are not recognized

### ISSUE THREAD

**Issue by adrianiftode** [cezarypiatek/MappingGeneratorReleases#3]
I'm frequently initializing objects from JSONs via advanced object scaffolding, however I noticed the Newtonsoft attributes are not taken in consideration.

So for example having this class

```
public class X
{
  [JsonProperty("some valid property name in the json")]
   public string Property {get; set;}
}
```
and the JSON
```
{
  "some valid property name in the json": "property value"
}
```

Then when I initialized the object from JSON, the `Property` initialization is not included.

version: 2023.3.56

Also possible to configure the serializer at all?

For example let's that I have some custom serialization. Possible MappingGenerator  to provide an Interface that I could implement and then to have a way MappingGenerator to load that assembly (given by a path), and to use the implementation to deserialize the JSON and the to use the deserialized values in the properties initialization? 

Btw this tool is a time and money saver, kudos for building it.

**Comment by cezarypiatek** [comment]
Thanks for reporting this issue.
Adding an option to load third-party plugins is always problematic.

Which serializer settings are you interested in? Maybe I could expose them via the UI.

In the meantime, I will try to check why the attributes are ignored.

**Comment by cezarypiatek** [comment]
Ok, currently MappingGenrator doesn't check attributes on the target side while matching values with fields. I can try to implement that.

**Comment by adrianiftode** [comment]
Even so it would be difficult to provide custom converters via UI, and also consider now we have two major JSON serializers.

**Comment by cezarypiatek** [comment]
Can you provide examples of your custom converters? What are those custom rules?

**Comment by cezarypiatek** [comment]
I  added support for `[JsonProperty]`, `[JsonPropertyName]`, and `[DataMember]` attributes. Please try the latest version and let me know if that solves your problem.

**Comment by adrianiftode** [comment]
The JSON initialization doesn't seem to work at all now.

**Comment by cezarypiatek** [comment]
Do you get any error messages? Can you provide a sample code that you are using? Just checked the latest revision and it's working fine

![image](https://github.com/cezarypiatek/MappingGeneratorReleases/assets/7759991/51e9f932-a257-401e-b825-745704401435)

**Comment by adrianiftode** [comment]
You are right, it works fine.

The reason I said it wasn't working at all after the update is because I tested with a different DTO class than the initial one before I raised this issue.

So I was puzzled why it wasn't working, and I realized for that DTO, the annotations were defined via System.Runtime.Serialization, ie DataContract, DataMember (WCF world).

Not sure what is the best way MappingGenerator to handle this (maybe simply use DataContractJsonSerializer?), but I would expect at least to ignore them. Currently no values are considered, when JSON initialization is used with these attributes.

As per the fine grained configuration, consider simply the fact one can work with Newtonsoft, other with System.Text.Json. That could be one very good reason to make this plugable.

Then there are custom converters and here are some use cases https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/converters-how-to?pivots=dotnet-7-0

**Comment by cezarypiatek** [comment]
MappingGenerator is not using any of mentioned deserializer because there's no actual deserialization performed under the hood. To scaffold object initialization I parse JSON with the parser provider by Newtonsoft and I try to match the targets with fields from the parser.
There's no way to use the actual deserializer because I don't have runtime info about the target type. I operate on the symbol info.


Since the last updates, when MappingGenerator is not able to match the source with the target using the actual field name, then it tries to fallback to data provided by the following attributes

- System.Runtime.Serialization.DataMemberAttribute
- Newtonsoft.Json.JsonPropertyAttribute
- System.Text.Json.Serialization.JsonPropertyNameAttribute


I wonder why it won't work with your WCF case. Can you provide and example of that DTO and JSON payload?

**Comment by adrianiftode** [comment]
I think this one is reproductible

![image](https://github.com/cezarypiatek/MappingGeneratorReleases/assets/13752939/d8b35f50-3c7d-4faa-ad91-b57078a77815)

**Comment by cezarypiatek** [comment]
what do you expect in this case? Maybe I don't understand something but the result looks good to me. Field with [DataMember] has no value set for Name.

**Comment by adrianiftode** [comment]
That's a wrong print, sorry about that. Here is a better one. After you mentioned the Name property, I then realized this is the issue.
I expect both properties to be initialized, as the Name is used only when the intention is to override.

![image](https://github.com/cezarypiatek/MappingGeneratorReleases/assets/13752939/4638f193-cae8-4af1-9ab5-fb9b9bac6571)

**Comment by cezarypiatek** [comment]
Great, thanks to your example, I managed to reproduce and fix the issue. The new version has been released.
I would appreciate if you could make another round of testing.

**Comment by adrianiftode** [comment]
Looks fine now, thanks.
