### ISSUE TITLE
[Question] Is Mapping Generator feature complete?

### ISSUE THREAD

**Issue by modabas** [cezarypiatek/MappingGeneratorReleases#4]
...or are there any planned additional features for near future?

**Comment by cezarypiatek** [comment]
There's no such thing as " feature complete" in software development, there's always room for improvement. 😃 
I'm planning to continue MappingGenerator development. Can you explain the purpose of this question?

**Comment by modabas** [comment]
> I'm planning to continue MappingGenerator development. Can you explain the purpose of this question?

Sure, to learn about new features (if any) that will become available during yearly subscription in addition to current features.

**Comment by cezarypiatek** [comment]
I always do my best to list all new features and other changes in the release notes under every release  https://github.com/cezarypiatek/MappingGeneratorReleases/releases
